/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/anothernew.glb')
  const { actions } = useAnimations(animations, group)

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime() / 2;
    group.current.rotation.x = a;
  });


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0, 7.22, 0]} rotation={[Math.PI / 2, 0, 0]} scale={32.79} />
        <group name="Cylinder001" position={[2.93, 2.6, 0.36]} rotation={[1.34, 0, 1.57]} scale={0.43} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[1.53, 2.61, 0.35]} rotation={[1.34, 0, 1.57]} scale={0.43} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[2.98, 2.6, 0.36]} rotation={[0.82, 1.57, 2.09]} scale={[9.25, 0.44, 21.56]} />
      </group>
    </group>
  )
}

useGLTF.preload('/anothernew.glb')
