/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { OrbitControls } from "@react-three/drei";

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/tube.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[3.07, 140.04, -117.47]} rotation={[1.88, 0.94, -2.92]} />
        <group name="Camera" position={[-0.03, 75.76, -66.39]} rotation={[1.56, 0, 3.12]} scale={94.67/5} />
        <group name="Empty" position={[0, 7.22, 0]} rotation={[Math.PI / 2, 0, 0]} scale={32.79/5} />
        <group name="Cylinder001" position={[-8.78, 2.59, 0.36]} rotation={[-1.34, 0, -1.57]} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[-5.54, 2.6, 0.35]} rotation={[-1.34, 0, -1.57]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[-8.89, 2.59, 0.36]} rotation={[0.54, -1.57, 0.31]} scale={[21.39/5, 1.02/5, 49.89/5]} />
      </group>
      <OrbitControls />
    </group>
  )
}

useGLTF.preload('/tube.glb')
// 94.67
